# Generated by Django 3.2.2 on 2021-05-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210520_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='Salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='application_deadline',
        ),
        migrations.DeleteModel(
            name='JobListing',
        ),
    ]
